from __future__ import annotations

DATA_TYPE_MORNING_CHECK_CODE = "MORNING_CHECK_RECORD"
DATA_TYPE_MORNING_CHECK_LABEL = "晨检消息记录"
DATA_TYPE_AI_BOX_CODE = "AI_BOX_RECORD"
DATA_TYPE_AI_BOX_LABEL = "AI盒子消息记录"
DATA_TYPE_SAMPLING_CODE = "SAMPLING_RECORD"
DATA_TYPE_SAMPLING_LABEL = "留样消息记录"

SOURCE_DEVICE_AUTO = "DEVICE_AUTO"

PROCESS_RESULT_SUCCESS = "SUCCESS"
PROCESS_RESULT_PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
PROCESS_RESULT_FAILED = "FAILED"

ALERT_TYPE_HIGH_TEMP = "HIGH_TEMP"
ALERT_TYPE_NO_MASK = "NO_MASK"

TEMPERATURE_ALERT_THRESHOLD = 37.3
TEMPERATURE_NORMAL_THRESHOLD = 37.3
TEMPERATURE_HIGH_THRESHOLD = 38.0

AI_BOX_EVENT_TYPES = {
    "HELMET_DETECT": "头盔检测",
    "MASK_DETECT": "口罩检测",
    "SMOKE_DETECT": "烟雾检测",
    "FIRE_DETECT": "明火检测",
    "PERSON_DETECT": "人员检测",
    "UNIFORM_DETECT": "工服检测",
}


def get_temperature_status(temperature: float) -> str:
    if temperature >= TEMPERATURE_HIGH_THRESHOLD:
        return "HIGH"
    if temperature >= TEMPERATURE_NORMAL_THRESHOLD:
        return "ELEVATED"
    return "NORMAL"

__all__ = [
    "DATA_TYPE_MORNING_CHECK_CODE",
    "DATA_TYPE_MORNING_CHECK_LABEL",
    "DATA_TYPE_AI_BOX_CODE",
    "DATA_TYPE_AI_BOX_LABEL",
    "DATA_TYPE_SAMPLING_CODE",
    "DATA_TYPE_SAMPLING_LABEL",
    "SOURCE_DEVICE_AUTO",
    "PROCESS_RESULT_SUCCESS",
    "PROCESS_RESULT_PARTIAL_SUCCESS",
    "PROCESS_RESULT_FAILED",
    "ALERT_TYPE_HIGH_TEMP",
    "ALERT_TYPE_NO_MASK",
    "TEMPERATURE_ALERT_THRESHOLD",
    "TEMPERATURE_NORMAL_THRESHOLD",
    "TEMPERATURE_HIGH_THRESHOLD",
    "AI_BOX_EVENT_TYPES",
    "get_temperature_status",
]
